### ISSUE TITLE
Орфографические ошибки

### ISSUE THREAD

**Issue by SuleymanovKamil** [tinkoff-mobile-tech/AcquiringSdk_IOS#177]
В тестовом приложении и самом SDK множество ошибок. Например:
rebuidIdCards
cardListViewConfigration
parentPatmentId

В XCode есть функция проверки правописания.

**Comment by ivanglushko** [comment]
Привет! Спасибо.
Завели задачу MIC-6512 приоритет минор, пока не известно когда доберемся, но она теперь в беклоге

**Comment by ivanglushko** [comment]
Привет в версии 3.0 поправили опечатки.
Закрываю issue по истечению сроков, если проблема актуальна просьба открыть новый issue.
