### ISSUE TITLE
После подтверждения СБП в банковском приложении и возврате в приложение не скрывается шторка "ожидается оплата"

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/AcquiringSdk_IOS#223]
### Описание бага
После подтверждения СБП в банковском приложении и возврате в приложение не скрывается шторка "ожидается оплата"

### После каких действий возникает ошибка
1. В приложении ввожу сумму
2. Нажимаю "оплатить по СБП"
3. В списке банков, выбираю Тинькофф
4. Перехожу в приложение Тинькофф банка и подтверждаю платеж
5. Возвращаюсь в приложение

### Ожидаемое поведение
После подтверждения платежа и возврате в приложение шторка "ожидается оплата" скрылась и произошел переход на результирующий экран

### Что происходит на деле
Происходит переход на результирующий экран но отображается шторка "ожидается оплата"

### Окружение и настройки:

- **Версия компонента:** [e.g. 2.12.2]
- **Версия iOS:** [e.g. iOS 16]
- **Версия Xcode:** [e.g. Xcode 14]
- **Версия Swift:** [e.g. Swift 5.2]
- **Используемый девайс/симулятор:** [e.g. iPhone 12]

**Comment by akhaman** [comment]
Привет! Уточни пожалуйста, кнопка СБП располагается на платежной форме эквайринга или на экране вашего приложения?

**Comment by VNGXR** [comment]
> Привет! Уточни пожалуйста, кнопка СБП располагается на платежной форме эквайринга или на экране вашего приложения?

Привет. У нас аналогичная проблема. Кнопка СБП располагается на экране нашего приложения, вызывает **urlSBPPaymentViewController(acquiringPaymentStageConfiguration...**.

**Comment by rmurad93** [comment]
> Привет! Уточни пожалуйста, кнопка СБП располагается на платежной форме эквайринга или на экране вашего приложения?

Располагается на экране моего приложения.

**Comment by akhaman** [comment]
Принято! Взяли в работу

**Comment by akhaman** [comment]
Посмотрели информацию по данному платежу. Он не оплачен, соответственно SDK его еще обрабатывает и показывает лоадер. 

Почему платеж не прошел - лучше обратиться в поддержку, они подробнее проконсультируют

**Comment by akhaman** [comment]
Если посмотреть на запрос `v2/GetState`, отправляемый периодически после возвращения из банковского приложения, то можно увидеть, что статус платежа `FORM_SHOWED`. Это означает, что экран с формой оплаты в банковском приложении отобразился пользователю, но оплаты не было

**Comment by VNGXR** [comment]
Нет, v2/GetState сменяется с FORM_SHOWED на CONFIRMED, отрабатывает результирующий колбек, а боттомшит "Ожидаем подтверждения платежа" остаётся висеть.

До оплаты:
```
{
    "Amount": 2400,
    "ErrorCode": "0",
    "Message": "OK",
    "OrderId": "АЗС32-16/12/22-53483",
    "Params": [
        {
            "Key": "Route",
            "Value": "ACQ"
        }
    ],
    "PaymentId": "2107559751",
    "Status": "FORM_SHOWED",
    "Success": true,
    "TerminalKey": "нашКлюч"
}
```

После оплаты:
```
{
    "Amount": 2400,
    "ErrorCode": "0",
    "Message": "OK",
    "OrderId": "АЗС32-16/12/22-53483",
    "Params": [
        {
            "Key": "Route",
            "Value": "QR"
        },
        {
            "Key": "Source",
            "Value": "qrsbp"
        }
    ],
    "PaymentId": "2107559751",
    "Status": "CONFIRMED",
    "Success": true,
    "TerminalKey": "нашКлюч"
}
```

**Comment by akhaman** [comment]
Здесь недопонимание вышло, теперь все ясно)
Если вызывается каллбек, вам нужно самостоятельно вызвать `dismiss` у полученного ранее контроллера и обработать соответствующим образом полученный статус. 

Сейчас ведутся работы по редизайну флоу оплаты СБП, добавим отдельную точку входа. Там избавим вас от необходимости самостоятельно управлять навигацией

**Comment by akhaman** [comment]
@rmurad93 
Вероятно сообщение выше и вам должно помочь

**Comment by ivanglushko** [comment]
Закрываю issue по истечению сроков, если проблема актуальна просьба открыть новый issue.
