### ISSUE TITLE
Добавьте пожалуйста поддержку рекуррентных переводов СБП

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/AcquiringSdk_IOS#224]
Добавьте пожалуйста поддержку рекурретных переводов СБП в SDK

**Comment by ivanglushko** [comment]
Привет! Поддержка рекуррентных переводов СБП планируется на 2023 год (не в первом квартале точно).

**Comment by rmurad93** [comment]
Подскажите пожалуйста, появилось ли понимание когда будут рекуррентные платежи СБП? Это очень сильно влияет на мой бизнес

**Comment by ivanglushko** [comment]
Привет!

По вопросам будущих доработок лучше обращаться к вашему персональному менеджеру или в нашу поддержку, с указанием описания вашей потребности.
Пока мы, к сожалению, не можем сориентировать вас по возможным срокам.
А в рамках этого канала мы можем помочь решить проблемы и вопросы, которые относятся к действующему функционалу [технические вопросы]
