### ISSUE TITLE
Нет возможности отследить и обработать удаление карты

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/AcquiringSdk_IOS#225]
При удалении карты из списка карт не срабатывает делегат

**Comment by ivanglushko** [comment]
Привет Мурад!
---
В версии 3.0 появился новый метод он возращает контроллер для карт(не вью контроллер) `ICardsController`.
Он позволяет работать с картами, добавлять / удалять / получать список карт - дергает методы на беке.
По поводу когда обновляется карты, только после посылаемых запросов (на удаление/ добавление).

Обработать можно в completion:e он вернет результат http запроса на удаление карты.
 
<img width="1005" alt="Screenshot 2023-05-24 at 13 54 36" src="https://github.com/tinkoff-mobile-tech/AcquiringSdk_IOS/assets/36343782/7096beae-2f04-4fca-b1f9-37f0173ac227">
<img width="1036" alt="Screenshot 2023-05-24 at 13 55 00" src="https://github.com/tinkoff-mobile-tech/AcquiringSdk_IOS/assets/36343782/d9a99a88-ecbe-4da4-a757-27cd865261da">
