### ISSUE TITLE
После удаления карты клиентом и повтором запросе карт клиента – возвращается удаленная карта

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/AcquiringSdk_IOS#228]
### Описание бага
После удаления карты клиентом и повтором запросе карт клиента – возвращается удаленная карта.

Для просмотра и удаления карт используется presentCardList

### После каких действий возникает ошибка
1. Пользователь выполнил платеж с признаком рекуррентного
2. Перешел в настройки и удалил карту
3. При запросе списка карт (cardListDataProvider.fetch) возвращается ранее клиентом удаленная карта

### Ожидаемое поведение
В callback-е cardListDataProvider.fetch нет ранее удаленной карты или статус карты равен "deleted"

### Что происходит на деле
В callback-е cardListDataProvider.fetch приходит ранее удаленна карта со статусом равен "active"

### Логи
[TinkoffASDKCore.PaymentCard(pan: "123456******1234", cardId: "123456", status: TinkoffASDKCore.PaymentCardStatus.active, parentPaymentId: Optional(123456), expDate: Optional("0101"))]

- **Версия компонента:** [e.g. 2.12.2]
- **Версия iOS:** [e.g. iOS 16]
- **Версия Xcode:** [e.g. Xcode 16]
- **Версия Swift:** [e.g. Swift 5.2]
- **Используемый девайс/симулятор:** [e.g. iPhone 12]

**Comment by ivanglushko** [comment]
Привет!
Не могу вопроизвести, у юзера одна карта? Или несколько в списке карт?

**Comment by ivanglushko** [comment]
В комплишене вернулся только массив карт или была и ошибка?

**Comment by rmurad93** [comment]
У пользователя была одна карта. Удалил одну карту, в интерфейсе не отображалась но если дернуть cardListDataProvider.fetch возвращается именно эта одна карта

**Comment by ivanglushko** [comment]
Я правильно понимаю что вы открываете экран с картами путем `presentCardList`.
Потом по закрытию экрана сами дергаете `cardListDataProvider.fetch(startHandler: (() -> Void)?, completeHandler: @escaping (ObjectType?, Error?) -> Void)`? И получаете там не валидный список карт? 
Не пробовали снифить запросы сдк(`v2/RemoveCard && v2/GetCardList`) ? Точно ли карта удалилась?

В общем нужно больше вводных)

**Comment by rmurad93** [comment]
"вы открываете экран с картами путем presentCardList" – да
"Потом по закрытию экрана сами дергаете cardListDataProvider.fetch(startHandler: (() -> Void)?, completeHandler: @escaping (ObjectType?, Error?) -> Void)" – да
"И получаете там не валидный список карт?" – да

"Не пробовали снифить запросы сдк(v2/RemoveCard && v2/GetCardList) ? Точно ли карта удалилась?" – не снифил, но в списке карт на экране presentCardList не было

**Comment by ivanglushko** [comment]
1. Окружение тестовое или продовое? 
2. Сможете ли воспроизвести кейс?

**Comment by rmurad93** [comment]
1. ПРОД
2. Попробую вечером
