### ISSUE TITLE
Если уже есть привязанная карта у customerKey, то при привязке новой карты возвращается значение id первой карты

### ISSUE THREAD

**Issue by vazh2100miura** [tinkoff-mobile-tech/AcquiringSdk_IOS#240]
### Описание бага
При привязке карты с типом 3dshold, если уже есть у customerKey  ранее привязанная карта, то при привязке второй карты возвращается cardId первой карты:

```
private func attachCardWithNativeScreen(customerKey: String) {
    let configuration = AcquiringViewConfiguration()
    
    tinkoffAcquiringUI?.addCardNeedSetCheckTypeHandler = {
        PaymentCardCheckType.hold3DS
    }

    tinkoffAcquiringUI?.presentAddCardView(on: uiController!, customerKey: customerKey, configuration: configuration, completeHandler: { res in
        do {
            let paymentCard = try res.get()
            paymentCard?.cardId // Здесь всегда один и тот же id - id первой карты, а не новой
        } catch {}
    })
}
```

### После каких действий возникает ошибка
1.Привязать первую карту через  presentAddCardView
2. считать paymentCard?.cardId и запомнить как cardOneId
3. Привязать вторую карту карту через  presentAddCardView
4. Считать paymentCard?.cardId и запомнить как cardTwoId
5. Получить cardOneId равное cardTwoId

### Ожидаемое поведение
cardOneId НЕравен cardTwoId

### Что происходит на деле
cardOneId равен CardTwoId

### Окружение и настройки:

- **Версия компонента:** [e.g. 2.5.0]
2.13.1
- **Версия iOS:** [e.g. iOS 15]
IOS 13
- **Версия Xcode:** [e.g. Xcode 13]
13.2.1
- **Версия Swift:** [e.g. Swift 5.2]

- **Используемый девайс/симулятор:** [e.g. iPhone 13] 
Iphone 13

**Comment by AlexanderBrygin** [comment]
Добрый день, спасибо! Рассмотрели кейс, взяли в исправление.

**Comment by ivanglushko** [comment]
Закрываю issue по истечению сроков, если проблема актуальна на версии сдк 3.0 просьба открыть новый issue.
