### ISSUE TITLE
Пропало логгирование сетевых запросов

### ISSUE THREAD

**Issue by Pluxury** [tinkoff-mobile-tech/AcquiringSdk_IOS#283]
### Описание бага
Пропало логгирование сетевых запросов 

### После каких действий возникает ошибка
после обновления на 2.16.0

### Ожидаемое поведение
Сетевые запросы логируются

### Что происходит на деле
Сетевые запросы не логгируются
### Логи
Не нахожу использование LoggerDelegate после передачи его в init AcquiringUISDK. В старых версиях логи хотя бы в консоль писались, а сейчас вообще тишина.

**Comment by ivanglushko** [comment]
Привет! 
В версии 3.0 в `AcquiringSdkConfiguration` появился `logger: ILogger` там подобных проблем больше нет.
Она является актуальной.
