### ISSUE TITLE
Всё время выбрана карта по-умолчанию

### ISSUE THREAD

**Issue by nickwhale1004** [tinkoff-mobile-tech/AcquiringSdk_IOS#284]
### Описание бага
> Если вызвать метод `.presentPaymentView(on: vc, acquiringPaymentStageConfiguration: stageConfig, configuration: config, tinkoffPayDelegate: nil)` передать в него `stageConfig`, в котором задан объект `PaymentInitData`, с заданной картой, всё равно открывается карта по-умолчанию. Хотя в шапке модели PaymentInitData приведена документация, в которой сказано, что если передать в `"DATA":{"DefaultCard":"894952"};`, то именно переданная карта будет выбрана (или пустое поле ввода карты, если передано значение "none"). 

https://www.tinkoff.ru/kassa/develop/api/payments/init-request/

В android sdk есть поле selectedCard для передачи cardId, у нас почему-то нет.

### После каких действий возникает ошибка
> 1. Инициализация `PaymentInitData` с параметром` paymentFormData = ["DefaultCard": model.cardId ?? "none"]`
> 2. Инициализация `stageConfig = AcquiringPaymentStageConfiguration(paymentStage: .init(paymentData: data))`
> 3. Вызов `sdk.presentPaymentView(on: vc, acquiringPaymentStageConfiguration: stageConfig, configuration: config, tinkoffPayDelegate: nil)`

### Ожидаемое поведение
> Откроется vc, в котором выбрана указанная карта (либо пустое поле, либо карта по-умолчанию - в соответствии с документацией)

### Что происходит на деле
> PaymentInitData отправляется на сервер только в момент нажатия кнопки оплаты -> перед оплатой vc открывается с выбранной картой по-умолчанию.

### Окружение и настройки:
- **Версия компонента:** 2.16.0
- **Версия iOS:** iOS 16
- **Версия Xcode:** Xcode 14
- **Версия Swift:** Swift 5.2
- **Используемый девайс/симулятор:** iPhone 14

**Comment by ivanglushko** [comment]
<img width="1169" alt="Screenshot 2023-05-24 at 14 12 52" src="https://github.com/tinkoff-mobile-tech/AcquiringSdk_IOS/assets/36343782/0155296d-b84e-4355-95a5-b94e01ba4ddd">

Привет!В версии 3.0 Изменился API и был переработан сдк. Используйте новый `IPaymentController` если вам нужно самим управлять оплатой (без нашего UI) 
presentPaymentView  стал -> presentMainForm
Там юзер может выбрать нужный способ оплаты и карту.

<img width="50%" alt="Screenshot 2023-05-24 at 14 08 11" src="https://github.com/tinkoff-mobile-tech/AcquiringSdk_IOS/assets/36343782/52ded4fb-83ea-4c21-8fcb-90cc5e79299d">
<img width="50%" alt="Screenshot 2023-05-24 at 14 08 24" src="https://github.com/tinkoff-mobile-tech/AcquiringSdk_IOS/assets/36343782/6e444b11-3baf-4475-bb65-10c8f4f9f11e">
