### ISSUE TITLE
Размер бинарника слишком большой, ошибка ITMS-90865

### ISSUE THREAD

**Issue by alkozin** [tinkoff-mobile-tech/AcquiringSdk_IOS#316]
### Описание бага
Размер бинарника либы слишком большой, получаем ошибку ITMS-90865: Thinned app clip size is too large
при заливке в стор. Ассеты и так удаляем руками при каждом обновлении pod.

### После каких действий возникает ошибка
Обновил pods с версии 2.10.4 до 2.17.0

### Ожидаемое поведение
Бинарник будет весить меньше половины приложения. Мы используем AppClip.

В версии 2.10.4 нет папки TinkoffASDKUI/ThirdParty
Начиная со следующей 2.11.0 она появляется. В ней бинарник TdsSdkIos.

### Что происходит на деле
TdsSdkIos весит 5,6 mb.

<img width="1051" alt="Screenshot 2023-03-12 at 22 44 26" src="https://user-images.githubusercontent.com/2376017/224555786-fda74f97-fe4d-437d-b0cd-5c555f5ba6f9.png">

### Окружение и настройки:

- **Версия компонента:** 2.17.0
- **Версия iOS:** iOS 15
- **Версия Xcode:** 14.2.0
- **Версия Swift:** Swift 5.2
- **Используемый девайс/симулятор:** iPhone 13 Pro Max

**Comment by akhaman** [comment]
И если не секрет, о каком приложении идет речь?

**Comment by alkozin** [comment]
> Добрый день! TdsSdkIos появился в SDK по требованию национальной платежной системы. Эта библиотека, разработанная подрядчиком, необходима для выполнения некоторых видов платежей с 3DS без использования WebView
> 
> На данный момент тяжко представить, как можно помочь вам решить проблему. Хочу уточнить: действительно ли SDK эквайринга нужен в AppClips ?

Добрый день!
Мы принимаем оплату за бензин в приложении:
NFC метка и App Clip Code наклеены на пистолет АЗС. 

https://user-images.githubusercontent.com/2376017/224920481-52b87887-9062-489c-8e51-23eb03ae489f.MOV

**Comment by alkozin** [comment]
> И если не секрет, о каком приложении идет речь?

https://azsenergia.ru/
Открывайте в Safari, откроется карточка App Clip

**Comment by alkozin** [comment]
Можем как-то повлиять на размер TdsSdkIos?

**Comment by akhaman** [comment]
Пока исследуем возможные варианты решения вашей проблемы. Есть вероятность, что будет возможность сжать эту библиотеку, поставляемую подрядчиком. Также одним из возможных вариантов решения, способных благоприятно сказаться на итоговый размер поставляемых библиотек, будет переход на статическую линовку прямых и транзитивных зависимостей. 

Конкретные сроки обозначить пока тяжело. Тред оставим открытым, в случае каких-то обновлений оповестим в том числе и здесь

**Comment by alkozin** [comment]
Спасибо, продолжаем пользоваться эквайрингом.

**Comment by alkozin** [comment]
> @alkozin не смотрели еще?)

Спасибо, увидел. На следующей неделе попробуем и отпишусь 👍🏼

**Comment by ivanglushko** [comment]
@alkozin есть новости? :)

**Comment by ivanglushko** [comment]
Закрываю тред из-за неактивности.
Если еще есть вопросы пишите тут, переоткроем.
В дальнейшем асдк переедет на статическую линковку.
