### ISSUE TITLE
Отсутствует инициализатор для AgentData и SupplierInfo

### ISSUE THREAD

**Issue by edementiev** [tinkoff-mobile-tech/AcquiringSdk_IOS#349]
Скажите пожалуйста для AgentData и SupplierInfo из инициализаторов доступны и существуют только init(from decoder)
Существуют ли другие варианты использования или примеры в exemple?

**Comment by edementiev** [comment]
Привет, да, конечно в receipt,  в поле agentData

было бы значительно удобнее, чем через Decode работать, да и прозрачнее бы было

**Comment by edementiev** [comment]
Если будет возможность сделать побыстрее апачем в /master, это будет здорово, т.к. как раз функционал агентских чеков делаем

**Comment by ivanglushko** [comment]
> Если будет возможность сделать побыстрее апачем в /master, это будет здорово, т.к. как раз функционал агентских чеков делаем

Привет! Сделал минорный релиз с правкой этого issue https://github.com/tinkoff-mobile-tech/AcquiringSdk_IOS/releases/tag/2.19.0
