### ISSUE TITLE
Кастомный экран финального статуса

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/AcquiringSdk_IOS#388]
### Описание
> Ранее я использовал кастомный экран по результату платежа. Он был адаптирован с учетом моего сценария и аудитории. Сейчас всегда после платежа отображается реализация от Тинькофф. Как её скрыть?

**Comment by ivanglushko** [comment]
Привет! Можешь пожалуйста предоставить больше информации. И скрины если возможно. Какие методы вызываешь и что используешь с сдк?

**Comment by rmurad93** [comment]
Я перешел на новую версию SDK 3.0.
Использую метод presentMainForm(on: vc, paymentFlow: paymentFlow, configuration: configuration) { result in }
