### ISSUE TITLE
Логика обновления данных о банковских картах

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/AcquiringSdk_IOS#389]
Опишите пожалуйста:
1. Условия при которых обновляются данные по банковским картам.
2. Как часто?
3. В каких случаях нужно самостоятельно обновлять данные?
4. Обновляются ли данные по картам после платежа?

**Comment by ivanglushko** [comment]
Привет! По этому вопросу стоит обратиться в поддержку [acq_help@tinkoff.ru](mailto:acq_help@tinkoff.ru)
