### ISSUE TITLE
Нет возможности использовать свой результирующий экран как и раньше

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/AcquiringSdk_IOS#401]
**В версии 2.19** и ниже была возможность использовать свой результирующий экран. Это было удобно и позволяло лучше адаптировать сценарий под клиента.

**В версии 3.0** при использовании presentMainForm, presentTinkoffPay, presentSBPBanksList вы реализовали результирующий экран **без возможности** использовать свою реализацию. Из-за этого ограничения к сожалению прилось откатить все изменения на предыдущую версию 2.19

Делать форк вашей библиотеки и адаптировать под свой сценарий лишает возможности в будущем обновлять версию SDK. Я очень прошу вернуть возможность использовать свой регулирующий экран после выполнения платежа.

**Comment by ivanglushko** [comment]
Привет!
На данный запрос, дали понять что рассмотрят для взятия в беклог, к сожалению пока никаких сроков дать не можем.

Еще из вариантов использовать сущности которые проводят платеж с использованием вашего UI.

<img width="1150" alt="Screenshot 2023-05-29 at 12 34 34" src="https://github.com/tinkoff-mobile-tech/AcquiringSdk_IOS/assets/36343782/b0277b05-6d4b-4aba-963a-0e1ce66058cf">
