### ISSUE TITLE
SDK не возвращает событие при закрытии окна

### ISSUE THREAD

**Issue by Cheeezcake** [tinkoff-mobile-tech/AcquiringSdk_IOS#74]
Здравствуйте.
Обнаружил следующую проблему: 
Если открыть окно оплаты со включенным полем email, ввести email (окно переходит в полноэкранный режим), затем ввести CVC, то при закрытии окна не возвращается никакого события => невозможно обработать отмену оплаты пользователем.
Вместо поля email можно начать вводить номер другой карты (свайпнув на добавление новой), затем вернуться, ввести CVC и поймать то же молчание при закрытии.
Тестировщик уверяет, что ловил (единожды) то же отсутствие событие и на успешную оплату, а не на закрытие.

Кейс "email + закрытие окна" легко воспроизводится в ASDKSample.

**Comment by grishamsc** [comment]
Здравствуйте.
Вышла версия 2.4.2 с исправлением.

**Comment by Cheeezcake** [comment]
Здравствуйте, благодарю вас!

**Comment by Cheeezcake** [comment]
Тестировщик смог повторить кейс. При открытии окна оплаты необходимо потянуть окно вверх до перехода в полноэкранный режим (с кнопкой-крестиком для закрытия), отпустить и еще раз немного потянуть вниз-вверх, отпустить. После этих манипуляций событие не приходит по закрытию и свайпом и кнопкой-крестиком.

**Comment by iosdevlicard** [comment]
@grishamsc призываю Вас :D

**Comment by grishamsc** [comment]
@Cheeezcake Здравствуйте. 
Можно вас попросить приложить видео от тестировщика? Прикладываю видео с манипуляциями, которые попробовал воспроизвести по вашему описанию, но, кажется, что-то упускаю.

https://user-images.githubusercontent.com/2726726/128412011-d5e63aeb-a20b-4783-9ce0-f1202c507fb0.mov

**Comment by ivanglushko** [comment]
Закрываю тред по истечению сроков, вышла версия 3.0 в ней такой проблемы не должно быть.
