### ISSUE TITLE
Как открыть оплату по PaymentID?

### ISSUE THREAD

**Issue by ridbrain** [tinkoff-mobile-tech/AcquiringSdk_IOS#78]
Инициализация платежа происходит на бэке, который возвращает PaymentID. Как инициализировать платёж без передачи в приложение terminalPassword и publicKey?

**Comment by grishamsc** [comment]
Здравствуйте.
На текущий момент в СДК нет такой возможности. В ближайшее время выйдет версия, в которой требования указывать `terminalPassword` не будет.

**Comment by ridbrain** [comment]
Есть примерные сроки?

**Comment by laranight** [comment]
Здравствуйте! Вероятнее всего, выпустим версию в конце лета с этими доработками

**Comment by ridbrain** [comment]
Вот это ближайшее время( что ж, ждём...

**Comment by laranight** [comment]
Есть доработки внутри разных систем, поэтому времени требуется больше.

**Comment by grishamsc** [comment]
@ridbrain 
Здравствуйте. В релизе 2.5.0 убрана необходимость передавать в СДК пароль.

**Comment by StIch0** [comment]
` let paymentStageConfiguration = AcquiringPaymentStageConfiguration(paymentStage: .finish(paymentId: paymentId))
      
        uiSdk.presentPaymentView(
          on: viewController,
          acquiringPaymentStageConfiguration: paymentStageConfiguration,
          configuration: acquiringViewConfiguration(
            cartItems: cartItems,
            email: email,
            phone: phone),
          tinkoffPayDelegate: nil)`
          
          Добрый день. у меня paymentId создается на сервере 

          я его передаю как параметр в AcquiringPaymentStageConfiguration
          
          при вызове uiSdk.presentPaymentView получаю бесконечную загрузку 


![Simulator Screen Shot - iPhone X - 2022-12-12 at 14 06 28](https://user-images.githubusercontent.com/21060259/206958408-8dd948df-d605-47b2-a562-7fdf507a1309.png)


подскажите, в чем может быть ошибка ?

**Comment by ivanglushko** [comment]
Закрываю issue по истечению сроков, если проблема актуальна просьба открыть новый issue.
