### ISSUE TITLE
Failed to present in-app payment interface: Error Domain=PKPassKitErrorDomain Code=4 "Отсутствует авторизация идентификатора продавца merchant.tcsbank.ApplePayTestMerchantId"

### ISSUE THREAD

**Issue by ajdos** [tinkoff-mobile-tech/AcquiringSdk_IOS#79]
Здравствуйте! При оплате через ApplePay возникает данная ошибка и окно выбора карты не открывается.
Логи:
🛬 End request: https://securepay.tinkoff.ru/v2/Init, with response data:
{"Success":true,"ErrorCode":"0","TerminalKey":"1616764698425","Status":"NEW","PaymentId":"599506317","OrderId":"72B26F29-5F7A-415D-8E6B-B92B74A5378D","Amount":51900}
2021-06-14 17:50:48.961432+0300 CronDelivery[722:181366] [General] Failed to present in-app payment interface: Error Domain=PKPassKitErrorDomain Code=4 "Отсутствует авторизация идентификатора продавца merchant.tcsbank.ApplePayTestMerchantId" UserInfo={NSLocalizedDescription=Отсутствует авторизация идентификатора продавца merchant.tcsbank.ApplePayTestMerchantId}
2021-06-14 17:50:48.962256+0300 CronDelivery[722:181139] [General] Connection to remote alert view service failed

**Comment by ajdos** [comment]
Пшшшш.... приём... Сокол вызывает орла приём.... пшшш...

**Comment by evkorm** [comment]
Здравствуйте!
Столкнулся с такой же проблемой. Решения так и нет?

**Comment by Assass1n1191** [comment]
I had exactly same issue and the problem was that I had a typo in code, in merchantIdentifier in PKPaymentRequest object

**Comment by alkozin** [comment]
Hello!
I found this solution:

```
var c = AcquiringUISDK.ApplePayConfiguration()
        c.merchantIdentifier = "merchant.com......"
        Acquiring.sdk.presentPaymentApplePay(on:
```

**Comment by ivanglushko** [comment]
Всем привет, извиняюсь что так и не решили вашу проблему в срок. Если она актуальна просьба открыть новый issue. 
Вышла версия 3.0 в ней сдк был сильно переработан. Если проблема сохраняется просьба открыть новый issue.
Закрываю issue по истечению сроков.

**Comment by ivanglushko** [comment]
@ajdos понимаю 😅, но я тут пару месяцев на сдк) 
В основное время занимались рефакторингом и редизайном версии 3.0 которая вот недавно вышла. 
Разбираю issues хочу актуализировать их чтобы не было такой же истории как тут.
