### ISSUE TITLE
Отображение экрана оплаты

### ISSUE THREAD

**Issue by rozmarica** [tinkoff-mobile-tech/AcquiringSdk_IOS#90]
Добрый день.

Есть необходимость использовать кастомный NavigationController для всего приложения, на видео видно, как при этом отображается экран оплаты. Подскажите, пожалуйста, как можно избежать отображения скруглений и черты для сворачивания (она не работает) ? И можно ли задать плавную анимацию отображения контроллера по тапу на введение данных карты (сейчас он резко открывается на весь экран) ?

Второй вопрос про AgentData и SupplierInfo: как их передать, если инициализатор только init(from decoder) ?

https://user-images.githubusercontent.com/83059939/131496543-27892841-2ca9-40ed-9475-8108b8d56175.mov

**Comment by laranight** [comment]
Добрый день! 
В текущей реализации такая кастомизация не предусмотрена. Но мы планируем пересмотреть логику работы UI в SDK и, возможно, в будущих релизах добавим и эту кастомизацию.

**Comment by ivanglushko** [comment]
Закрываю issue по истечению сроков
