### ISSUE TITLE
Проблема с подключение SDK.

### ISSUE THREAD

**Issue by show6time** [tinkoff-mobile-tech/AcquiringSdk_IOS#93]
Добрый день.

При использование pods в Xcode 12.5.1, base sdk = 13.0
Ловится ошибка не дающая создать билд или запустить.

Multiple commands produce '/Users/mrtrent/Library/Developer/Xcode/DerivedData/ProjectName-acdohcvggppjlibdlnqapplsdnkd/Build/Products/Debug-iphonesimulator/ProjectName.app/Assets.car':
1) Target 'ProjectName' (project 'ProjectName') has compile command with input '/Users/mrtrent/Documents/Projects/ProjectName-ios/ProjectNameApp/ProjectName.xcassets'
2) That command depends on command in Target 'ProjectName' (project 'ProjectName'): script phase “[CP] Copy Pods Resources”

duplicate output file '/Users/mrtrent/Library/Developer/Xcode/DerivedData/ProjectName-acdohcvggppjlibdlnqapplsdnkd/Build/Products/Debug-iphonesimulator/ProjectName.app/Assets.car' on task: PhaseScriptExecution [CP] Copy Pods Resources /Users/mrtrent/Library/Developer/Xcode/DerivedData/ProjectName-acdohcvggppjlibdlnqapplsdnkd/Build/Intermediates.noindex/ProjectName.build/Debug-iphonesimulator/ProjectName.build/Script-E8CD570900A59E1FC671E394.sh

Названия для Project и TargetName заменены на ProjectName.

Вот мануал в качестве временного решения:
https://dev.to/kylefoo/xcode-12-new-build-system-warns-multiple-commands-produce-assets-car-56im

Просьба:
Господа разработчики, пожалуйста воспользуйтесь п.5 из ссылки выше.
"The most proper way to resolve this is to identify the Pods that use the deprecated resources in its Podspec, update them to resource_bundles instead."

**Comment by show6time** [comment]
Кратко.
Для тех у кого возникли проблемы с интеграцией на XCode 12.5.1 & pod v.1.11.2
Начиная с asset car, продолжая crash из-за xib key-value.

Сделан форк - https://github.com/show6time/AcquiringSdk_IOS

Раскидано на spec.resource_bundles и ряд правок.

**Comment by OneSman7** [comment]
Господа разработчики, эта проблема будет решена?
Невозможно статически слинковать sdk.
Описаный способ решения должен сработать.

**Comment by ivanglushko** [comment]
Закрываю issue по истечению сроков, если проблема актуальна просьба открыть новый issue.
---
В планах перевести СДК на статическую линковку (летом скорее всего сделаем)
