### ISSUE TITLE
Не работает оплата Apple Pay (используются два разных merchantId)

### ISSUE THREAD

**Issue by VladislavYU** [tinkoff-mobile-tech/AcquiringSdk_IOS#94]
Ситуация следующая, в приложении используется данные от 2 разных терминала Тинькофф, которые имеют разные сертификаты merchant. Настройки в терминала в Тинькофф одинаковые, переведы в оплату на мобильном приложении. На первой организации работает отлично и оплата банковской картой, и оплата Apple Pay без ошибок, а вот у второй организации работает только оплата банковской картой, а при оплате Apple Pay выдает ошибку "Ошибка шифрования карточных даных"
![Screenshot 2021-09-23 at 17 51 03](https://user-images.githubusercontent.com/18311398/135155932-0ce52870-2c69-4fa9-bb1d-1ed068e3e1aa.png)
.

В чем может быть причина и как побороть эту проблему?

**Comment by ivanglushko** [comment]
Закрываю issue по истечению сроков.
В данный момент Apple Pay полностью отключен из-за санкций.
